name: Unit tests for BackEnd Services

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run Nuke
      run: ./build.sh UnitTest --Cover --Configuration Debug
    - name: Create Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: BackEnd Services Coverage
        color: brightgreen
        path: coverage/report.xml
        gist-filename: code-coverage.json
        gist-id: 3375eaca628d8c57c854ebb56d2b6b14
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"
